import { StatusBar, StyleSheet } from 'react-native'
import { colors, spacing } from '../constants/theme'

const screenGutter = spacing.md
const screenBottomPadding = 120
const cornerRadius = 8
const unifiedShadow = {
	shadowColor: '#000',
	shadowOpacity: 0.1,
	shadowOffset: { width: 0, height: 4 },
	shadowRadius: 10,
	elevation: 3,
}

export const appStyles = StyleSheet.create({
	app: {
		flex: 1,
		backgroundColor: colors.surface,
		paddingTop: StatusBar.currentHeight ?? 0,
	},
	appSplash: {
		backgroundColor: colors.splash,
	},
	screen: {
		flex: 1,
	},
	screenPadding: {
		flex: 1,
		padding: spacing.md,
		backgroundColor: colors.splash,
	},
	scrollContent: {
		padding: spacing.md,
		paddingBottom: 108,
		gap: spacing.md,
		backgroundColor: colors.splash,
	},
	pageTitleWrap: {
		gap: 6,
	},
	pageTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	pageBackButton: {
		alignSelf: 'flex-start',
		paddingVertical: 2,
		paddingRight: 8,
	},
	pageBackButtonText: {
		color: '#125ED0',
		fontSize: 13,
		fontWeight: '800',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	pageTitle: {
		color: '#121212',
		fontSize: 22,
		fontWeight: '800',
	},
	pageSubtitle: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 18,
	},
	splashScreen: {
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: colors.splash,
	},
	splashLogo: {
		width: 300,
		height: 240,
	},
	welcomeLogo: {
		width: '80%',
		maxWidth: 320,
		height: 250,
	},
	welcomeScreen: {
		flex: 1,
		backgroundColor: colors.splash,
		paddingHorizontal: spacing.md,
		paddingBottom: spacing.md,
	},
	welcomeContent: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		paddingTop: 42,
		paddingBottom: 20,
		gap: 150,
	},
	welcomeActions: {
		width: '100%',
		alignItems: 'center',
		paddingBottom: 6,
	},
	welcomePrimaryButton: {
		backgroundColor: '#1A1A1A',
		...unifiedShadow,
	},
	welcomePrimaryButtonLabel: {
		color: '#F1F1F1',
		fontSize: 15,
		fontWeight: '800',
		letterSpacing: 0.7,
	},
	welcomeTextButton: {
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 8,
		paddingHorizontal: 12,
	},
	welcomeTextButtonLabel: {
		color: colors.text,
		fontSize: 16,
		fontWeight: '800',
		letterSpacing: 0.6,
	},
	loginScreen: {
		flex: 1,
		backgroundColor: colors.splash,
	},
	loginContent: {
		flexGrow: 1,
		backgroundColor: colors.surface,
		paddingTop: 20,
		paddingHorizontal: screenGutter,
		paddingBottom: 24,
	},
	loginTitle: {
		color: colors.text,
		fontSize: 22,
		fontWeight: '800',
		marginTop: 12,
		marginBottom: 34,
	},
	loginFields: {
		gap: 22,
	},
	loginFieldWrap: {
		gap: 8,
	},
	loginInput: {
		paddingHorizontal: 0,
		paddingVertical: 4,
		fontSize: 14,
		lineHeight: 20,
		fontWeight: '600',
		color: colors.text,
		backgroundColor: 'transparent',
	},
	loginDivider: {
		height: 1,
		backgroundColor: 'rgba(26, 26, 26, 0.18)',
		marginTop: 1,
	},
	loginPasswordRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	loginEyeButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	loginForgot: {
		color: '#125ED0',
		fontSize: 16,
		fontWeight: '500',
		marginTop: 2,
	},
	loginButtonWrap: {
		marginTop: 44,
	},
	loginPrimaryButton: {
		backgroundColor: '#1A1A1A',
		...unifiedShadow,
	},
	loginPrimaryButtonLabel: {
		color: '#F1F1F1',
		fontSize: 15,
		fontWeight: '800',
		letterSpacing: 0.7,
	},
	registerAccountScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	registerAccountContent: {
		flexGrow: 1,
		justifyContent: 'flex-start',
		paddingTop: 16,
		paddingHorizontal: screenGutter,
		paddingBottom: 24,
		backgroundColor: colors.surface,
	},
	registerHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		marginBottom: 56,
	},
	registerBackButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerAccountTopWrap: {
		gap: 16,
	},
	registerAccountTitle: {
		color: '#121212',
		fontSize: 42,
		lineHeight: 46,
		fontWeight: '800',
	},
	registerAccountFieldBlock: {
		gap: 8,
	},
	registerAccountInput: {
		color: '#1A1A1A',
		fontSize: 14,
		lineHeight: 20,
		fontWeight: '600',
		paddingVertical: 4,
		paddingHorizontal: 0,
	},
	registerAccountDivider: {
		height: 1,
		backgroundColor: '#C9CDD6',
		marginTop: 1,
	},
	registerPasswordFieldBlock: {
		gap: 6,
	},
	registerPasswordInputRow: {
		minHeight: 40,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	registerPasswordInput: {
		flex: 1,
		color: '#1A1A1A',
		fontSize: 14,
		lineHeight: 20,
		fontWeight: '600',
		paddingVertical: 2,
		paddingHorizontal: 0,
	},
	registerPasswordDivider: {
		height: 1,
		backgroundColor: '#C9CDD6',
		marginTop: 0,
	},
	registerPasswordEyeButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerPasswordHint: {
		color: '#9DA2AE',
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '600',
	},
	registerAccountBottomWrap: {
		marginTop: 325,
		paddingBottom: 0,
	},
	registerAccountPrimaryButton: {
		minHeight: 45,
		borderRadius: cornerRadius,
		backgroundColor: '#15171B',
		...unifiedShadow,
	},
	registerAccountPrimaryButtonText: {
		color: '#F5F5F5',
		fontSize: 15,
		fontWeight: '900',
		letterSpacing: 0.5,
	},
	card: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		padding: spacing.md,
		borderWidth: 1,
		borderColor: colors.border,
		...unifiedShadow,
		gap: spacing.md,
	},
	heroCard: {
		padding: spacing.lg,
	},
	kicker: {
		color: colors.secondary,
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 1.4,
	},
	heroTitle: {
		color: colors.text,
		fontSize: 28,
		fontWeight: '800',
		lineHeight: 34,
	},
	homeTitle: {
		color: colors.text,
		fontSize: 30,
		fontWeight: '800',
	},
	heroText: {
		color: colors.muted,
		fontSize: 15,
		lineHeight: 22,
	},
	homeContent: {
		flexGrow: 1,
		backgroundColor: colors.surface,
		paddingHorizontal: screenGutter,
		paddingTop: 68,
		paddingBottom: 24,
		gap: 18,
	},
	homeScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	homeHeader: {
		alignItems: 'center',
		paddingTop: 2,
		gap: 8,
	},
	homeLogo: {
		width: '100%',
		maxWidth: 300,
		height: 180,
		marginBottom: 4,
	},
	homeKicker: {
		color: colors.text,
		fontSize: 15,
		fontWeight: '800',
		letterSpacing: 0.8,
		textTransform: 'uppercase',
	},
	homeSubtitle: {
		color: '#6D7789',
		fontSize: 11,
		lineHeight: 16,
		textAlign: 'center',
		maxWidth: 250,
	},
	homePrimaryButton: {
		backgroundColor: colors.primary,
		minHeight: 78,
		borderRadius: cornerRadius,
		...unifiedShadow,
	},
	homePrimaryButtonLabel: {
		fontSize: 16,
		fontWeight: '800',
		letterSpacing: 0.8,
	},
	homeShortcutRow: {
		flexDirection: 'row',
		gap: 12,
		justifyContent: 'space-between',
	},
	homeShortcutCard: {
		flex: 1,
		minHeight: 140,
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		alignItems: 'center',
		justifyContent: 'center',
		gap: 12,
		...unifiedShadow,
	},
	homeShortcutIconBox: {
		width: 54,
		height: 54,
		borderRadius: cornerRadius,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F4F8FF',
	},
	homeShortcutLabel: {
		color: '#125ED0',
		fontSize: 13,
		fontWeight: '800',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	registerScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	registerHeaderBar: {
		backgroundColor: colors.secondary,
		paddingHorizontal: screenGutter,
		paddingTop: 28,
		paddingBottom: 16,
		minHeight: 78,
		justifyContent: 'flex-end',
	},
	registerHeaderTitle: {
		color: colors.text,
		fontSize: 22,
		lineHeight: 26,
		fontWeight: '900',
		letterSpacing: 0.5,
	},
	registerScroll: {
		flex: 1,
	},
	registerContent: {
		paddingHorizontal: screenGutter,
		paddingTop: 22,
		paddingBottom: screenBottomPadding,
	},
	registerCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 14,
		paddingVertical: 14,
		...unifiedShadow,
		gap: 14,
	},
	registerSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	registerSectionTitleTextBlue: {
		color: colors.secondary,
		fontSize: 15,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	registerSubsection: {
		gap: 10,
	},
	registerSubTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	registerSubTitleText: {
		color: colors.text,
		fontSize: 12,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	registerDropZone: {
		minHeight: 110,
		borderWidth: 1,
		borderStyle: 'dashed',
		borderColor: '#7AA7FF',
		borderRadius: cornerRadius,
		backgroundColor: '#FFFFFF',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 16,
		paddingVertical: 16,
		gap: 6,
	},
	registerDropZoneIconWrap: {
		width: 48,
		height: 48,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerDropZoneTitle: {
		color: colors.text,
		fontSize: 14,
		fontWeight: '800',
		textAlign: 'center',
	},
	registerDropZoneText: {
		color: '#8F8F98',
		fontSize: 12,
		fontWeight: '600',
		textAlign: 'center',
	},
	registerBehaviorList: {
		gap: 10,
	},
	registerBehaviorItem: {
		flexDirection: 'row',
		alignItems: 'center',
		minHeight: 44,
		backgroundColor: '#F2F2F2',
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
	},
	registerCheckbox: {
		width: 18,
		height: 18,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: '#A8A8A8',
		backgroundColor: colors.surface,
		alignItems: 'center',
		justifyContent: 'center',
		marginRight: 12,
	},
	registerCheckboxActive: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
	},
	registerBehaviorLabel: {
		color: colors.text,
		fontSize: 14,
		fontWeight: '800',
	},
	registerDateRow: {
		flexDirection: 'row',
		gap: 10,
	},
	registerDateField: {
		flex: 1,
		minHeight: 42,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: '#79A7EB',
		backgroundColor: '#FDFEFF',
		paddingHorizontal: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	registerDateFieldText: {
		color: colors.text,
		fontSize: 13,
		fontWeight: '700',
	},
	registerActionsRow: {
		flexDirection: 'row',
		gap: 12,
		marginTop: 2,
	},
	registerSaveButton: {
		flex: 1,
		minHeight: 44,
		...unifiedShadow,
	},
	registerCancelButton: {
		flex: 1,
		minHeight: 44,
		...unifiedShadow,
	},
	registerActionButtonLabel: {
		fontSize: 12,
		fontWeight: '900',
		letterSpacing: 0.5,
	},
	mapsScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	mapsHeaderBar: {
		backgroundColor: colors.secondary,
		paddingHorizontal: screenGutter,
		paddingTop: 28,
		paddingBottom: 16,
		minHeight: 78,
		justifyContent: 'flex-end',
	},
	mapsHeaderTitle: {
		color: colors.surface,
		fontSize: 22,
		lineHeight: 26,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.5,
	},
	mapsContent: {
		paddingHorizontal: screenGutter,
		paddingTop: 8,
		paddingBottom: screenBottomPadding,
		gap: 8,
	},
	mapsFilterCard: {
		padding: 12,
		gap: 10,
		borderRadius: cornerRadius,
		borderWidth: 0,
		backgroundColor: '#F7F8FA',
		...unifiedShadow,
	},
	mapsFilterTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	mapsFilterHint: {
		color: colors.muted,
		fontSize: 12,
		lineHeight: 18,
	},
	mapsFilterRow: {
		flexDirection: 'row',
		gap: 8,
	},
	mapsFilterButton: {
		flex: 1,
		minHeight: 32,
		borderWidth: 1.2,
		borderColor: '#79A7EB',
		borderRadius: cornerRadius,
		backgroundColor: colors.surface,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 12,
		gap: 5,
	},
	mapsFilterButtonActive: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
	},
	mapsFilterButtonIcon: {
		marginTop: -1,
	},
	mapsFilterButtonLabel: {
		color: colors.text,
		fontSize: 9,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.2,
	},
	mapsFilterButtonLabelActive: {
		color: colors.surface,
	},
	mapsMapCard: {
		padding: 0,
		overflow: 'hidden',
		borderRadius: cornerRadius,
		borderWidth: 0,
		...unifiedShadow,
		minHeight: 490,
	},
	mapsLegendCard: {
		padding: 12,
		gap: 12,
		borderRadius: cornerRadius,
		borderWidth: 0,
		...unifiedShadow,
	},
	mapsLegendTitle: {
		color: colors.secondary,
		fontSize: 12,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 1.1,
	},
	mapsLegendRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
	},
	mapsLegendItem: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		minWidth: '42%',
	},
	mapsLegendDot: {
		width: 9,
		height: 9,
		borderRadius: 9,
		backgroundColor: colors.primary,
	},
	mapsLegendLabel: {
		color: colors.text,
		fontSize: 11,
		fontWeight: '700',
	},
	gridCardTitle: {
		color: colors.text,
		fontSize: 18,
		fontWeight: '700',
	},
	gridCardText: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 20,
	},
	fieldWrapper: {
		gap: spacing.xs,
	},
	fieldLabel: {
		color: colors.text,
		fontSize: 13,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	textField: {
		backgroundColor: '#F8F9FB',
		borderWidth: 1,
		borderColor: colors.border,
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: 14,
		fontSize: 15,
		color: colors.text,
	},
	textFieldMultiline: {
		minHeight: 110,
		textAlignVertical: 'top',
	},
	actionButton: {
		minHeight: 52,
		borderRadius: cornerRadius,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: spacing.md,
		borderWidth: 1,
		borderColor: 'transparent',
	},
	actionButtonFullWidth: {
		width: '100%',
	},
	actionButtonContent: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		width: '100%',
	},
	actionButtonIconLeft: {
		marginRight: 12,
	},
	actionButtonIconRight: {
		marginLeft: 12,
	},
	actionButtonPrimary: {
		backgroundColor: colors.primary,
	},
	actionButtonSecondary: {
		backgroundColor: colors.secondary,
	},
	actionButtonOutline: {
		backgroundColor: 'transparent',
		borderColor: colors.secondary,
	},
	actionButtonGhost: {
		backgroundColor: 'transparent',
	},
	actionButtonGhostText: {
		color: colors.text,
		fontSize: 17,
		fontWeight: '800',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	actionButtonPressed: {
		opacity: 0.85,
		transform: [{ scale: 0.99 }],
	},
	actionButtonDisabled: {
		opacity: 0.45,
	},
	actionButtonText: {
		color: colors.surface,
		fontSize: 15,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	actionButtonTextOutline: {
		color: colors.secondary,
	},
	actionButtonTextGhost: {
		color: colors.primary,
	},
	headerWrap: {
		gap: spacing.xs,
		marginBottom: spacing.sm,
	},
	backButton: {
		alignSelf: 'flex-start',
		paddingHorizontal: spacing.sm,
		paddingVertical: spacing.xs,
		borderRadius: cornerRadius,
		backgroundColor: '#EAF1FD',
	},
	backButtonText: {
		color: colors.secondary,
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
	},
	headerTitle: {
		color: colors.text,
		fontSize: 26,
		fontWeight: '800',
	},
	headerSubtitle: {
		color: colors.muted,
		fontSize: 14,
		lineHeight: 20,
	},
	sectionTitle: {
		color: colors.secondary,
		fontSize: 12,
		fontWeight: '800',
		textTransform: 'uppercase',
		letterSpacing: 1.1,
	},
	photoDropZone: {
		backgroundColor: '#F8FAFF',
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: '#B7CBEF',
		padding: spacing.md,
		gap: spacing.xs,
	},
	photoDropZoneTitle: {
		color: colors.text,
		fontSize: 16,
		fontWeight: '700',
	},
	photoDropZoneText: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 20,
	},
	infoText: {
		color: colors.text,
		fontSize: 14,
		lineHeight: 21,
	},
	chipRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: spacing.sm,
	},
	chip: {
		backgroundColor: '#F4F7FD',
		borderWidth: 1,
		borderColor: '#C7D4F0',
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: spacing.sm,
	},
	chipActive: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
	},
	chipText: {
		color: colors.text,
		fontSize: 12,
		fontWeight: '700',
	},
	chipTextActive: {
		color: colors.surface,
	},
	rowGap: {
		gap: spacing.sm,
	},
	mapCard: {
		padding: spacing.sm,
	},
	mapFrame: {
		minHeight: 360,
		borderRadius: cornerRadius,
		overflow: 'hidden',
		backgroundColor: '#DCEBFF',
		borderWidth: 1,
		borderColor: '#BCD2F7',
	},
	mapGrid: {
		...StyleSheet.absoluteFillObject,
		opacity: 0.35,
		backgroundColor: 'transparent',
	},
	mapPulseOne: {
		position: 'absolute',
		top: '25%',
		left: '23%',
		width: 110,
		height: 110,
		borderRadius: 110,
		backgroundColor: 'rgba(242, 32, 31, 0.2)',
	},
	mapPulseTwo: {
		position: 'absolute',
		top: '52%',
		right: '16%',
		width: 86,
		height: 86,
		borderRadius: 86,
		backgroundColor: 'rgba(242, 32, 31, 0.24)',
	},
	mapPulseThree: {
		position: 'absolute',
		bottom: '18%',
		left: '48%',
		width: 72,
		height: 72,
		borderRadius: 72,
		backgroundColor: 'rgba(242, 32, 31, 0.22)',
	},
	mapMarkerOne: {
		position: 'absolute',
		top: '23%',
		left: '25%',
		width: 14,
		height: 14,
		borderRadius: 14,
		backgroundColor: colors.primary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapMarkerTwo: {
		position: 'absolute',
		top: '54%',
		right: '18%',
		width: 14,
		height: 14,
		borderRadius: 14,
		backgroundColor: colors.primary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapMarkerThree: {
		position: 'absolute',
		bottom: '20%',
		left: '50%',
		width: 14,
		height: 14,
		borderRadius: 14,
		backgroundColor: colors.primary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapNestMarker: {
		position: 'absolute',
		top: '33%',
		left: '18%',
		width: 16,
		height: 16,
		borderRadius: 4,
		backgroundColor: colors.secondary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapControls: {
		position: 'absolute',
		top: spacing.md,
		right: spacing.md,
	},
	zoomBadge: {
		position: 'absolute',
		top: spacing.md,
		left: spacing.md,
		backgroundColor: 'rgba(255,255,255,0.96)',
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: spacing.xs,
	},
	countBadge: {
		position: 'absolute',
		bottom: spacing.md,
		right: spacing.md,
		backgroundColor: 'rgba(255,255,255,0.96)',
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: spacing.xs,
	},
	badgeText: {
		color: colors.text,
		fontSize: 12,
		fontWeight: '700',
	},
	historyScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	historyHeaderBar: {
		backgroundColor: colors.secondary,
		paddingHorizontal: screenGutter,
		paddingTop: 28,
		paddingBottom: 16,
		minHeight: 78,
		justifyContent: 'flex-end',
	},
	historyHeaderTitle: {
		color: colors.surface,
		fontSize: 22,
		lineHeight: 26,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.5,
	},
	historyContent: {
		paddingHorizontal: screenGutter,
		paddingTop: 12,
		paddingBottom: screenBottomPadding,
		gap: 12,
	},
	historySearchCard: {
		borderWidth: 0,
		borderRadius: cornerRadius,
		padding: 14,
		gap: 12,
		...unifiedShadow,
	},
	historySearchInputWrap: {
		minHeight: 42,
		borderWidth: 1.4,
		borderColor: '#82A9EC',
		borderRadius: cornerRadius,
		paddingHorizontal: 10,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		backgroundColor: '#FFFFFF',
	},
	historySearchInput: {
		flex: 1,
		color: '#1A1A1A',
		fontSize: 14,
		fontWeight: '500',
		paddingVertical: 0,
	},
	historyFilterButton: {
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: '#1F61C5',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 7,
	},
	historyFilterButtonText: {
		color: '#FFFFFF',
		fontSize: 13,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	historyRecordCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: '#DDDDDD',
		paddingHorizontal: 12,
		paddingVertical: 12,
		gap: 8,
		...unifiedShadow,
	},
	historyRecordTopRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
	},
	historyRecordIdBadge: {
		minWidth: 45,
		height: 26,
		borderRadius: cornerRadius,
		backgroundColor: '#F2201F',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 8,
	},
	historyRecordIdText: {
		color: '#FFFFFF',
		fontSize: 14,
		fontWeight: '900',
		letterSpacing: 0.2,
	},
	historyRecordDateRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	historyRecordDateText: {
		color: '#1A1A1A',
		fontSize: 16,
		fontWeight: '700',
	},
	historyRecordDateDot: {
		color: '#1A1A1A',
		fontSize: 16,
		fontWeight: '800',
	},
	historyRecordInfoRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	historyRecordInfoText: {
		color: '#1A1A1A',
		fontSize: 16,
		fontWeight: '600',
	},
	historyTagRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
		marginTop: 2,
	},
	historyTagChip: {
		paddingHorizontal: 10,
		paddingVertical: 5,
		borderRadius: cornerRadius,
		backgroundColor: '#D5E2F8',
	},
	historyTagChipText: {
		color: '#1F61C5',
		fontSize: 11,
		fontWeight: '800',
		textTransform: 'uppercase',
	},
	historyDetailButton: {
		marginTop: 4,
		minHeight: 38,
		borderRadius: cornerRadius,
		backgroundColor: '#1F61C5',
		alignItems: 'center',
		justifyContent: 'center',
	},
	historyDetailButtonText: {
		color: '#FFFFFF',
		fontSize: 13,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	historyEmptyWrap: {
		backgroundColor: '#F4F4F4',
		borderRadius: cornerRadius,
		padding: 16,
	},
	historyEmptyText: {
		color: '#595A62',
		fontSize: 13,
		fontWeight: '600',
		textAlign: 'center',
	},
	historyModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(0, 0, 0, 0.28)',
		justifyContent: 'flex-end',
	},
	historyModalCard: {
		backgroundColor: '#F1F1F1',
		borderTopLeftRadius: 12,
		borderTopRightRadius: 12,
		maxHeight: '84%',
	},
	historyModalHeader: {
		minHeight: 60,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: '#DDDDDD',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	historyModalTitle: {
		color: '#1F61C5',
		fontSize: 27,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	historyModalContent: {
		paddingHorizontal: 16,
		paddingTop: 14,
		paddingBottom: 18,
		gap: 16,
	},
	historyFilterSection: {
		gap: 8,
	},
	historyFilterSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	historyFilterSectionTitle: {
		color: '#2A2A2A',
		fontSize: 13,
		fontWeight: '900',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	historyDateLabelsRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingRight: 12,
	},
	historySmallLabel: {
		color: '#5E5E68',
		fontSize: 11,
		fontWeight: '700',
		width: '48%',
	},
	historyDateRow: {
		flexDirection: 'row',
		gap: 8,
	},
	historyDateInputWrap: {
		flex: 1,
		minHeight: 40,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: '#82A9EC',
		backgroundColor: '#FFFFFF',
		paddingHorizontal: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 6,
	},
	historyDateInput: {
		flex: 1,
		color: '#1A1A1A',
		fontSize: 13,
		fontWeight: '600',
		paddingVertical: 0,
	},
	historySingleInput: {
		minHeight: 40,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: '#82A9EC',
		backgroundColor: '#FFFFFF',
		paddingHorizontal: 12,
		color: '#1A1A1A',
		fontSize: 14,
		fontWeight: '500',
	},
	historyHalfInput: {
		flex: 1,
		minHeight: 40,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: '#82A9EC',
		backgroundColor: '#FFFFFF',
		paddingHorizontal: 12,
		color: '#1A1A1A',
		fontSize: 14,
		fontWeight: '600',
	},
	historyBehaviorList: {
		gap: 8,
	},
	historyBehaviorItem: {
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: '#E7E7E7',
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 10,
		gap: 10,
	},
	historyBehaviorCheckbox: {
		width: 18,
		height: 18,
		borderRadius: cornerRadius,
		borderWidth: 1.2,
		borderColor: '#A8A8A8',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#FFFFFF',
	},
	historyBehaviorCheckboxActive: {
		backgroundColor: '#1F61C5',
		borderColor: '#1F61C5',
	},
	historyBehaviorLabel: {
		color: '#1A1A1A',
		fontSize: 16,
		fontWeight: '700',
	},
	historyModalActions: {
		borderTopWidth: 1,
		borderTopColor: '#DDDDDD',
		paddingHorizontal: 16,
		paddingVertical: 10,
		flexDirection: 'row',
		gap: 10,
	},
	historyClearButton: {
		flex: 1,
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: '#E5E5E5',
		alignItems: 'center',
		justifyContent: 'center',
	},
	historyClearButtonText: {
		color: '#2A2A2A',
		fontSize: 12,
		fontWeight: '900',
		letterSpacing: 0.3,
		textTransform: 'uppercase',
	},
	historyApplyButton: {
		flex: 1,
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: '#1F61C5',
		alignItems: 'center',
		justifyContent: 'center',
	},
	historyApplyButtonText: {
		color: '#FFFFFF',
		fontSize: 12,
		fontWeight: '900',
		letterSpacing: 0.3,
		textTransform: 'uppercase',
	},
	recordDetailScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	recordDetailHeaderBar: {
		backgroundColor: '#125ED0',
		minHeight: 82,
		paddingTop: 30,
		paddingBottom: 14,
		paddingHorizontal: screenGutter,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	recordDetailBackButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	recordDetailHeaderTitle: {
		color: '#F1F1F1',
		fontSize: 22,
		lineHeight: 20,
		fontWeight: '900',
		letterSpacing: 0.5,
		textTransform: 'uppercase',
	},
	recordDetailContent: {
		paddingHorizontal: screenGutter,
		paddingTop: 8,
		paddingBottom: 24,
		gap: 18,
	},
	recordDetailNotFoundWrap: {
		paddingHorizontal: screenGutter,
		paddingTop: 12,
	},
	recordDetailIdBadge: {
		alignSelf: 'flex-start',
		minWidth: 50,
		height: 34,
		borderRadius: cornerRadius,
		backgroundColor: '#F2201F',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 12,
	},
	recordDetailIdText: {
		color: '#FFFFFF',
		fontSize: 14,
		fontWeight: '900',
		letterSpacing: 0.2,
		textTransform: 'uppercase',
	},
	recordDetailCard: {
		backgroundColor: '#F4F4F4',
		borderRadius: cornerRadius,
		paddingHorizontal: 18,
		paddingVertical: 18,
		gap: 14,
		...unifiedShadow,
	},
	recordDetailSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	recordDetailSectionTitle: {
		color: '#125ED0',
		fontSize: 15,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	recordDetailInfoList: {
		gap: 14,
	},
	recordDetailInfoRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 10,
	},
	recordDetailInfoTextWrap: {
		flex: 1,
		gap: 2,
	},
	recordDetailInfoLabel: {
		color: '#7A7D86',
		fontSize: 11,
		fontWeight: '900',
		letterSpacing: 0.7,
		textTransform: 'uppercase',
	},
	recordDetailValue: {
		color: '#1A1A1A',
		fontSize: 16,
		lineHeight: 20,
		fontWeight: '800',
	},
	recordDetailCoordinates: {
		color: '#5F6775',
		fontSize: 13,
		lineHeight: 17,
		fontWeight: '600',
	},
	recordDetailChipRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	recordDetailChip: {
		borderRadius: cornerRadius,
		backgroundColor: '#D5E2F8',
		paddingHorizontal: 12,
		paddingVertical: 7,
	},
	recordDetailChipText: {
		color: '#1F61C5',
		fontSize: 14,
		fontWeight: '900',
		letterSpacing: 0.3,
	},
	recordDetailImageGrid: {
		flexDirection: 'row',
		gap: 12,
	},
	recordDetailImagePlaceholder: {
		flex: 1,
		minHeight: 76,
		borderRadius: cornerRadius,
		backgroundColor: '#C8D2E2',
		alignItems: 'center',
		justifyContent: 'center',
	},
	recordDetailObservationText: {
		color: '#1A1A1A',
		fontSize: 15,
		lineHeight: 23,
		fontWeight: '700',
	},
	profileScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	profileHeaderBar: {
		backgroundColor: '#125ED0',
		minHeight: 82,
		justifyContent: 'flex-end',
		paddingBottom: 14,
		paddingHorizontal: screenGutter,
		paddingTop: 30,
	},
	profileSecondaryHeaderBar: {
		backgroundColor: '#125ED0',
		minHeight: 82,
		paddingTop: 30,
		paddingBottom: 14,
		paddingHorizontal: screenGutter,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	profileHeaderBackButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	profileHeaderTitle: {
		color: '#F1F1F1',
		fontSize: 22,
		lineHeight: 39,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	profileContent: {
		paddingHorizontal: screenGutter,
		paddingTop: 10,
		paddingBottom: screenBottomPadding,
		gap: 20,
	},
	profileHeroCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
		paddingVertical: 20,
		alignItems: 'center',
		gap: 8,
		...unifiedShadow,
	},
	profileAvatarCircle: {
		width: 104,
		height: 104,
		borderRadius: 104,
		borderWidth: 2.8,
		borderColor: '#1F61C5',
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 8,
	},
	profileHeroName: {
		color: '#141414',
		fontSize: 15,
		lineHeight: 18,
		fontWeight: '800',
		textAlign: 'center',
	},
	profileHeroEmail: {
		color: '#6C6E76',
		fontSize: 12,
		lineHeight: 15,
		fontWeight: '600',
		textAlign: 'center',
		marginBottom: 10,
	},
	profileEditButton: {
		minWidth: 114,
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 18,
	},
	profileEditButtonText: {
		color: '#FFFFFF',
		fontSize: 14,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	profileMenuCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 16,
		paddingVertical: 18,
		gap: 10,
		...unifiedShadow,
	},
	profileMenuTitle: {
		color: '#125ED0',
		fontSize: 14,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
		marginBottom: 2,
	},
	profileMenuItem: {
		minHeight: 42,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
		paddingHorizontal: 8,
	},
	profileMenuItemText: {
		color: '#121212',
		fontSize: 14,
		fontWeight: '700',
	},
	profileMenuItemTextLogout: {
		color: '#F2201F',
		fontSize: 14,
		fontWeight: '700',
	},
	changePasswordCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
		paddingVertical: 16,
		gap: 14,
		...unifiedShadow,
	},
	changePasswordFieldWrap: {
		gap: 5,
	},
	changePasswordLabelRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	changePasswordLabel: {
		color: '#111111',
		fontSize: 12,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	changePasswordInputRow: {
		minHeight: 42,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: '#79A7EB',
		backgroundColor: '#F4F4F4',
		paddingLeft: 10,
		paddingRight: 6,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	changePasswordInput: {
		minHeight: 42,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: '#79A7EB',
		backgroundColor: '#F4F4F4',
		paddingHorizontal: 10,
		color: '#1A1A1A',
		fontSize: 13,
		fontWeight: '600',
	},
	changePasswordInputNoPadding: {
		flex: 1,
		color: '#1A1A1A',
		fontSize: 14,
		fontWeight: '600',
		paddingVertical: 0,
	},
	changePasswordEyeButton: {
		width: 30,
		height: 30,
		alignItems: 'center',
		justifyContent: 'center',
	},
	changePasswordHint: {
		color: '#7D7F87',
		fontSize: 11,
		fontWeight: '600',
	},
	changePasswordActionsRow: {
		flexDirection: 'row',
		gap: 10,
		marginTop: 10,
	},
	changePasswordPrimaryAction: {
		flex: 1,
		minHeight: 42,
		borderRadius: cornerRadius,
		backgroundColor: '#FF1D1D',
		alignItems: 'center',
		justifyContent: 'center',
	},
	changePasswordPrimaryActionText: {
		color: '#FFFFFF',
		fontSize: 12,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	changePasswordSecondaryAction: {
		flex: 1,
		minHeight: 42,
		borderRadius: cornerRadius,
		backgroundColor: '#79A7E6',
		alignItems: 'center',
		justifyContent: 'center',
	},
	changePasswordSecondaryActionText: {
		color: '#F2F2F2',
		fontSize: 12,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	notificationsCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
		paddingVertical: 14,
		gap: 12,
		...unifiedShadow,
	},
	notificationsTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 7,
		paddingHorizontal: 4,
	},
	notificationsTitle: {
		color: '#125ED0',
		fontSize: 13,
		fontWeight: '900',
		letterSpacing: 0.4,
		textTransform: 'uppercase',
	},
	notificationsItem: {
		minHeight: 58,
		borderRadius: cornerRadius,
		backgroundColor: colors.background,
		paddingHorizontal: 10,
		paddingVertical: 8,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	notificationsTextWrap: {
		flex: 1,
		gap: 2,
	},
	notificationsItemTitle: {
		color: '#111111',
		fontSize: 14,
		fontWeight: '700',
	},
	notificationsItemSubtitle: {
		color: '#6F7179',
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '600',
	},
	aboutCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 14,
		paddingVertical: 16,
		gap: 12,
		...unifiedShadow,
	},
	aboutLogo: {
		alignSelf: 'center',
		width: 210,
		height: 110,
		marginTop: 8,
		marginBottom: 6,
	},
	aboutAppName: {
		color: '#125ED0',
		fontSize: 19,
		fontWeight: '900',
		textAlign: 'center',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	aboutVersion: {
		color: '#72757D',
		fontSize: 14,
		fontWeight: '700',
		textAlign: 'center',
		marginBottom: 10,
	},
	aboutSection: {
		gap: 6,
	},
	aboutSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	aboutSectionTitle: {
		color: '#125ED0',
		fontSize: 13,
		fontWeight: '900',
		letterSpacing: 0.3,
		textTransform: 'uppercase',
	},
	aboutBodyText: {
		color: '#111111',
		fontSize: 13,
		lineHeight: 25,
		fontWeight: '600',
	},
	aboutBulletRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 6,
	},
	aboutBulletDot: {
		color: '#F2201F',
		fontSize: 12,
		lineHeight: 24,
		fontWeight: '900',
	},
	aboutFooterDivider: {
		height: 1,
		backgroundColor: '#D9D9D9',
		marginTop: 6,
	},
	aboutFooterText: {
		color: '#7C7F86',
		fontSize: 11,
		lineHeight: 15,
		fontWeight: '500',
		textAlign: 'center',
	},
	profileHero: {
		alignItems: 'center',
	},
	avatarCircle: {
		width: 112,
		height: 112,
		borderRadius: 112,
		backgroundColor: '#EAF1FD',
		borderWidth: 3,
		borderColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	avatarInitial: {
		color: colors.secondary,
		fontSize: 46,
		fontWeight: '800',
	},
	profileName: {
		color: colors.text,
		fontSize: 20,
		fontWeight: '800',
		textAlign: 'center',
	},
	profileEmail: {
		color: colors.muted,
		fontSize: 13,
		textAlign: 'center',
	},
	toggleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: spacing.md,
	},
	toggleTextWrap: {
		flex: 1,
		gap: spacing.xs,
	},
	toggleTitle: {
		color: colors.text,
		fontSize: 15,
		fontWeight: '700',
	},
	toggleSubtitle: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 19,
	},
	listItem: {
		color: colors.text,
		fontSize: 14,
		lineHeight: 21,
	},
	bottomNav: {
		flexDirection: 'row',
		backgroundColor: colors.surface,
		borderTopWidth: 1,
		borderTopColor: colors.border,
		paddingTop: 8,
		paddingBottom: 10,
		paddingHorizontal: 6,
	},
	bottomNavItem: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 10,
		borderRadius: cornerRadius,
		marginHorizontal: 2,
		gap: 5,
	},
	bottomNavItemActive: {
		backgroundColor: '#FDECEC',
		...unifiedShadow,
	},
	bottomNavIcon: {
		marginBottom: -1,
	},
	bottomNavLabel: {
		color: '#8A8D95',
		fontSize: 10,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.7,
		textAlign: 'center',
	},
	bottomNavLabelActive: {
		color: colors.primary,
	},
})
