import { StyleSheet, ViewStyle, TextStyle } from 'react-native'
import { colors, spacing, radius } from '../constants/theme'

const screenGutter = spacing.md
const screenBottomPadding = 120
const cornerRadius = radius.md ?? 12
const unifiedShadow = {
	shadowColor: colors.text,
	shadowOpacity: 1,
	shadowOffset: { width: 0, height: 5 },
	shadowRadius: cornerRadius,
	elevation: 10,
}

// palette aliases — prefer theme colors, fallback to literals when needed
const palette = {
	primary: colors.primary,
	primaryDark: colors.primaryDark,
	secondary: colors.secondary,
	secondaryLight: colors.secondaryLight,
	background: colors.background,
	surface: colors.surface,
	text: colors.text,
	muted: colors.muted,
	border: colors.border,
	splash: colors.splash,
	white: colors.surface,
}

const baseCard: ViewStyle = {
	backgroundColor: palette.surface,
	borderRadius: cornerRadius,
	padding: spacing.md,
	borderWidth: 1,
	borderColor: palette.border,
	...unifiedShadow,
}

const basePrimaryButton: ViewStyle = {
	minHeight: 44,
	padding: 16,
	borderRadius: cornerRadius,
	alignItems: 'center',
	justifyContent: 'center',
	...unifiedShadow,
}

const basePrimaryButtonLabel: TextStyle = {
	color: palette.surface,
	fontSize: 15,
}

export const appStyles = StyleSheet.create<Record<string, any>>({
	app: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	appSplash: {
		backgroundColor: colors.splash,
	},
	screen: {
		flex: 1,
	},
	screenPadding: {
		flex: 1,
		padding: spacing.md,
		backgroundColor: colors.splash,
	},
	scrollContent: {
		padding: spacing.md,
		paddingBottom: 108,
		gap: spacing.md,
		backgroundColor: colors.splash,
	},
	pageTitleWrap: {
		flex: 1,
	},
	pageTitle: {
		color: palette.text,
		fontSize: 22,
	},
	pageSubtitle: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 18,
	},
	splashScreen: {
		justifyContent: 'center',
		color: colors.secondary,
		backgroundColor: colors.splash,
	},
	splashLogo: {
		width: 300,
		height: 240,
	},
	welcomeLogo: {
		width: '80%',
		maxWidth: 320,
		height: 250,
	},
	welcomeScreen: {
		flex: 1,
		backgroundColor: colors.splash,
		paddingHorizontal: spacing.md,
		paddingBottom: spacing.md,
	},
	welcomeContent: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		paddingTop: spacing.lg,
		gap: spacing.xl,
	},
	welcomeActions: {
		width: '100%',
		alignItems: 'center',
	},
	welcomePrimaryButton: {
    ...basePrimaryButton,
    elevation: 5,
		backgroundColor: colors.text,
	},
	welcomePrimaryButtonLabel: {
		...basePrimaryButtonLabel,
		color: colors.surface,
	},
	welcomeTextButton: {
		alignItems: 'center',
		paddingVertical: 8,
		paddingHorizontal: 12,
		backgroundColor: 'transparent',
	},
	welcomeTextButtonLabel: {
    color: colors.text,
    fontWeight: '600',
		fontSize: 16,
	},
	loginScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	loginContent: {
		flexGrow: 1,
		backgroundColor: colors.surface,
		paddingTop: 48,
		paddingHorizontal: screenGutter,
		paddingBottom: 24,
	},
	loginHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		marginBottom: 56,
	},
	loginTitle: {
		color: colors.text,
		fontSize: 22,
		lineHeight: 26,
	},
	loginBackButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	loginFields: {
		gap: 10,
	},
	loginFieldWrap: {
		gap: 5,
	},
	loginInput: {
		paddingHorizontal: 0,
		paddingVertical: 4,
		fontSize: 14,
		lineHeight: 20,
		color: colors.text,
		backgroundColor: 'transparent',
	},
	loginDivider: {
		height: 1,
		backgroundColor: colors.border,
	},
	loginPasswordRow: {
		flexDirection: 'row',
		alignItems: 'center',
    justifyContent: 'space-between',
  },
	loginPasswordInput: {
		flex: 1,
		minHeight: 36,
	},
	loginEyeButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	loginForgot: {
		color: colors.secondary,
		fontSize: 14,
	},
	loginButtonWrap: {
		marginTop: 44,
		alignItems: 'center',
	},
	loginPrimaryButton: {
		...basePrimaryButton,
		backgroundColor: palette.text,
		width: '86%',
		maxWidth: 360,
	},

	/* Shared auth styles for login/register screens */
	authContent: {
		flexGrow: 1,
		backgroundColor: colors.surface,
		paddingTop: 48,
		paddingHorizontal: screenGutter,
		paddingBottom: 24,
	},
	authButtonWrap: {
		marginTop: 44,
		alignItems: 'center',
	},
	authPrimaryButton: {
		...basePrimaryButton,
		backgroundColor: palette.text,
		width: '86%',
		maxWidth: 360,
	},
	authPrimaryButtonText: {
		...basePrimaryButtonLabel,
	},
	loginPrimaryButtonLabel: {
		...basePrimaryButtonLabel,
	},
	registerAccountScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	registerAccountContent: {
		flexGrow: 1,
		justifyContent: 'flex-start',
		paddingTop: 16,
		paddingHorizontal: screenGutter,
		paddingBottom: 24,
		backgroundColor: colors.surface,
	},
	registerHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		marginBottom: 56,
	},
	registerBackButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerAccountTopWrap: {
		gap: 16,
	},
	registerAccountTitle: {
		color: palette.text,
		fontSize: 42,
		lineHeight: 46,
	},
	registerAccountFieldBlock: {
		gap: 5,
	},
	registerAccountInput: {
		color: palette.text,
		fontSize: 14,
		lineHeight: 20,
		paddingVertical: 4,
		paddingHorizontal: 0,
	},
	registerAccountDivider: {
		height: 1,
		backgroundColor: palette.border,
		marginTop: 1,
	},
	registerPasswordFieldBlock: {
		gap: 2,
	},
	registerPasswordInputRow: {
		minHeight: 40,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	registerPasswordInput: {
		flex: 1,
		color: palette.text,
		fontSize: 14,
		lineHeight: 20,
		paddingVertical: 2,
		paddingHorizontal: 0,
	},
	registerPasswordDivider: {
		height: 1,
		backgroundColor: palette.border,
		marginTop: 0,
	},
	registerPasswordEyeButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerPasswordHint: {
		color: colors.muted,
		fontSize: 11,
		lineHeight: 14,
	},
	registerAccountBottomWrap: {
		marginTop: 325,
		paddingBottom: 0,
	},
	registerAccountPrimaryButton: {
		...basePrimaryButton,
		minHeight: 45,
		backgroundColor: palette.text,
	},
	registerAccountPrimaryButtonText: {
		color: palette.surface,
		fontSize: 15,
	},
	card: {
		...baseCard,
		gap: spacing.md,
	},
	heroCard: {
		padding: spacing.lg,
	},
	kicker: {
		color: palette.secondary,
		fontSize: 12,
		textTransform: 'uppercase',
	},
	heroTitle: {
		color: palette.text,
		fontSize: 28,
		lineHeight: 34,
	},
	homeTitle: {
		color: palette.text,
		fontSize: 30,
	},
	heroText: {
		color: palette.muted,
		fontSize: 15,
		lineHeight: 22,
	},
	homeContent: {
		flexGrow: 1,
		backgroundColor: palette.background,
		paddingHorizontal: screenGutter,
		paddingTop: '25%',
		paddingBottom: 24,
		gap: spacing.md,
	},
	homeScreen: {
    flex: 1,
	},
	homeHeader: {
    alignItems: 'center',
    marginTop: spacing.lg,
	},
	homeLogo: {
		width: '100%',
		maxWidth: 300,
		height: 180,
	},
	homeKicker: {
		color: palette.text,
		fontSize: 15,
		textTransform: 'uppercase',
	},
	homeSubtitle: {
		color: colors.muted,
		fontSize: 11,
		lineHeight: 16,
		textAlign: 'center',
		maxWidth: 250,
	},
	homePrimaryButton: {
		...basePrimaryButton,
		minHeight: 78,
		backgroundColor: palette.primary,
	},
	homePrimaryButtonLabel: {
		fontSize: 16,
	},
	homeShortcutRow: {
		flexDirection: 'row',
		gap: spacing.md,
		justifyContent: 'space-between',
	},
	homeShortcutCard: {
		flex: 1,
		minHeight: 140,
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		alignItems: 'center',
		justifyContent: 'center',
		...unifiedShadow,
	},
	homeShortcutIconBox: {
		width: 54,
		height: 54,
		borderRadius: cornerRadius,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'transparent',
	},
	homeShortcutLabel: {
		color: colors.secondary,
		fontSize: 13,
		textTransform: 'uppercase',
	},
	registerScreen: {
		flex: 1,
		backgroundColor: colors.background,
	},
	registerHeaderBar: {
		backgroundColor: colors.secondary,
		paddingHorizontal: screenGutter,
		paddingTop: 28,
		paddingBottom: 16,
		minHeight: 78,
		justifyContent: 'flex-end',
	},
	registerHeaderTitle: {
		color: colors.text,
		fontSize: 22,
		lineHeight: 26,
	},
	registerScroll: {
		flex: 1,
	},
	registerContent: {
		paddingHorizontal: screenGutter,
    paddingBottom: spacing.lg,
    paddingTop: spacing.lg,
	},
	registerCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 14,
		paddingVertical: 14,
		...unifiedShadow,
		gap: 14,
	},
	registerSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	registerSectionTitleTextBlue: {
		color: colors.secondary,
		fontSize: 15,
		textTransform: 'uppercase',
	},
	registerSubsection: {
		gap: 10,
	},
	registerSubTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	registerSubTitleText: {
		color: colors.text,
		fontSize: 12,
		textTransform: 'uppercase',
	},
	registerDropZone: {
		minHeight: 110,
		borderWidth: 1,
		borderStyle: 'dashed',
		borderColor: colors.secondaryLight,
		borderRadius: cornerRadius,
		backgroundColor: colors.surface,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 16,
		paddingVertical: 16,
		gap: spacing.md,
	},
	registerDropZonePressed: {
		backgroundColor: colors.splash,
		opacity: 0.1,
		transform: [{ scale: 0.99 }],
	},
	registerDropZoneIconWrap: {
		width: 48,
		height: 48,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerDropZoneTitle: {
		color: colors.text,
		fontSize: 14,
		textAlign: 'center',
	},
	registerDropZoneText: {
		color: colors.muted,
		fontSize: 12,
		textAlign: 'center',
	},
	registerImagePreviewGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	registerImagePreviewWrap: {
		position: 'relative',
		width: 72,
		height: 72,
	},
	registerImagePreview: {
		width: 72,
		height: 72,
		borderRadius: cornerRadius,
		backgroundColor: colors.border,
	},
	registerImageRemoveButton: {
		position: 'absolute',
		top: -6,
		right: -6,
		width: 24,
		height: 24,
		borderRadius: radius.pill,
		backgroundColor: colors.primary,
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 2,
		borderColor: colors.surface,
	},
	registerImageRemoveButtonPressed: {
		opacity: 0.8,
		transform: [{ scale: 0.96 }],
	},
	registerBehaviorList: {
		gap: spacing.md,
	},
	registerBehaviorItem: {
		flexDirection: 'row',
		alignItems: 'center',
		minHeight: 44,
		backgroundColor: colors.background,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
	},
	registerCheckbox: {
		width: 18,
		height: 18,
		borderRadius: cornerRadius,
		borderWidth: 1.4,
		borderColor: colors.border,
		backgroundColor: colors.surface,
		alignItems: 'center',
		justifyContent: 'center',
		marginRight: 12,
	},
	registerCheckboxActive: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
	},
	registerBehaviorLabel: {
		color: colors.text,
		fontSize: 14,
	},
	registerDateRow: {
		flexDirection: 'row',
		gap: 10,
	},
	registerDateField: {
		flex: 1,
		minHeight: 42,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.surface,
		paddingHorizontal: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	registerDateFieldText: {
		color: colors.text,
		fontSize: 13,
	},
	registerActionsRow: {
		flexDirection: 'row',
		gap: 12,
		marginTop: 2,
	},
	registerSaveButton: {
		flex: 1,
		minHeight: 44,
		...unifiedShadow,
	},
	registerCancelButton: {
		flex: 1,
		minHeight: 44,
		...unifiedShadow,
	},
	registerActionButtonLabel: {
		fontSize: 12,
	},
	mapsScreen: {
		flex: 1,
		backgroundColor: colors.background,
	},
	mapsHeaderBar: {
		backgroundColor: colors.secondary,
		paddingHorizontal: screenGutter,
		paddingTop: 28,
		paddingBottom: 16,
		minHeight: 78,
		justifyContent: 'flex-end',
	},
	mapsHeaderTitle: {
		color: colors.surface,
		fontSize: 22,
		lineHeight: 26,
		textTransform: 'uppercase',
	},
	mapsContent: {
		paddingHorizontal: screenGutter,
    paddingBottom: screenBottomPadding,
    paddingTop: spacing.lg,
		gap: 8,
	},
	mapsFilterCard: {
		gap: 10,
		borderRadius: cornerRadius,
    borderWidth: 0,
    marginBottom: spacing.md,
		backgroundColor: colors.surface,
		...unifiedShadow,
	},
	mapsFilterTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	mapsFilterHint: {
		color: colors.muted,
		fontSize: 12,
		lineHeight: 18,
	},
	mapsFilterRow: {
		flexDirection: 'row',
		gap: 8,
	},
	mapsFilterButton: {
		flex: 1,
		minHeight: 32,
		borderWidth: 1.2,
		borderColor: colors.secondaryLight,
		borderRadius: cornerRadius,
		backgroundColor: colors.surface,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 12,
		gap: 5,
	},
	mapsFilterButtonActive: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
	},
	mapsFilterButtonIcon: {
		marginTop: -1,
	},
	mapsFilterButtonLabel: {
		color: colors.text,
		fontSize: 9,
		textTransform: 'uppercase',
	},
	mapsFilterButtonLabelActive: {
		color: colors.surface,
	},
	mapsMapCard: {
		padding: 0,
		overflow: 'hidden',
		borderRadius: cornerRadius,
		borderWidth: 0,
		...unifiedShadow,
		height: '96%',
	},
	mapsLegendCard: {
		padding: 12,
		gap: 12,
		borderRadius: cornerRadius,
		borderWidth: 0,
		...unifiedShadow,
	},
	mapsLegendTitle: {
		color: colors.secondary,
		fontSize: 12,
		textTransform: 'uppercase',
	},
	mapsLegendRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
	},
	mapsLegendItem: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		minWidth: '42%',
	},
	mapsLegendDot: {
		width: 9,
		height: 9,
		borderRadius: 9,
		backgroundColor: colors.primary,
	},
	mapsLegendLabel: {
		color: colors.text,
		fontSize: 11,
	},
	gridCardTitle: {
		color: colors.text,
		fontSize: 18,
	},
	gridCardText: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 20,
	},
	fieldWrapper: {
		gap: spacing.xs,
	},
	fieldLabel: {
		color: colors.text,
		fontSize: 13,
		textTransform: 'uppercase',
	},
	textField: {
		backgroundColor: colors.background,
		borderWidth: 1,
		borderColor: colors.border,
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: 14,
		fontSize: 15,
		color: colors.text,
	},
	textFieldMultiline: {
		minHeight: 110,
		textAlignVertical: 'top',
	},
	actionButton: {
		minHeight: 52,
		borderRadius: cornerRadius,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: spacing.md,
		borderWidth: 1,
		borderColor: 'transparent',
	},
	actionButtonFullWidth: {
		width: '100%',
	},
	actionButtonContent: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		width: '100%',
	},
	actionButtonIconLeft: {
		marginRight: 12,
	},
	actionButtonIconRight: {
		marginLeft: 12,
	},
	actionButtonPrimary: {
		backgroundColor: colors.primary,
	},
	actionButtonSecondary: {
		backgroundColor: colors.secondary,
	},
	actionButtonOutline: {
		backgroundColor: 'transparent',
		borderColor: colors.secondary,
	},
	actionButtonGhost: {
		backgroundColor: 'transparent',
	},
	actionButtonGhostText: {
		color: colors.text,
		fontSize: 17,
		textTransform: 'uppercase',
	},
	actionButtonPressed: {
		opacity: 0.85,
		transform: [{ scale: 0.99 }],
	},
	actionButtonDisabled: {
		opacity: 0.45,
	},
	actionButtonText: {
		color: colors.surface,
		fontSize: 15,
		textTransform: 'uppercase',
	},
	actionButtonTextOutline: {
		color: colors.secondary,
	},
	actionButtonTextGhost: {
		color: colors.primary,
	},
	feedbackModalBackdrop: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'rgba(0, 0, 0, 0.28)',
		paddingHorizontal: screenGutter,
	},
	feedbackModalCard: {
		width: '100%',
		maxWidth: 360,
		alignItems: 'center',
		backgroundColor: colors.surface,
		borderRadius: radius.lg,
		paddingHorizontal: spacing.lg,
		paddingVertical: spacing.xl,
		gap: spacing.md,
		...unifiedShadow,
	},
	feedbackModalIconWrap: {
		width: 64,
		height: 64,
		borderRadius: radius.pill,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.splash,
	},
	feedbackModalTitle: {
		color: colors.secondary,
		fontSize: 20,
		textAlign: 'center',
		textTransform: 'uppercase',
	},
	feedbackModalMessage: {
		color: colors.muted,
		fontSize: 14,
		lineHeight: 20,
		textAlign: 'center',
	},
	feedbackModalButton: {
		width: '100%',
		minHeight: 44,
		marginTop: spacing.sm,
	},
	header: {
		backgroundColor: colors.secondary,
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 18,
		paddingVertical: 14,
		height: 56,
		width: '100%',
		alignSelf: 'stretch',
		...unifiedShadow,
	},
	headerLeft: {
		alignItems: 'center',
		justifyContent: 'center',
	},
	appHeaderTitle: {
    color: colors.surface,
    marginLeft: spacing.md,
		fontSize: 20,
		lineHeight: 22,
		fontWeight: '800',
		textTransform: 'uppercase',
	},
	headerRight: {
		alignItems: 'center',
		justifyContent: 'flex-end',
		marginLeft: spacing.sm,
	},
  headerActionButton: {
    marginTop: 1,
	},
	headerWrap: {
		gap: spacing.xs,
		marginBottom: spacing.sm,
	},
	backButton: {
		alignSelf: 'flex-start',
		paddingHorizontal: spacing.sm,
		paddingVertical: spacing.xs,
		borderRadius: cornerRadius,
		backgroundColor: colors.splash,
	},
	backButtonText: {
		color: colors.secondary,
		fontSize: 12,
		textTransform: 'uppercase',
	},
	headerTitle: {
		color: colors.text,
		fontSize: 26,
	},
	headerSubtitle: {
		color: colors.muted,
		fontSize: 14,
		lineHeight: 20,
	},
	sectionTitle: {
		color: colors.secondary,
		fontSize: 12,
		textTransform: 'uppercase',
	},
	photoDropZone: {
		backgroundColor: colors.splash,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: colors.secondaryLight,
		padding: spacing.md,
		gap: spacing.xs,
	},
	photoDropZoneTitle: {
		color: colors.text,
		fontSize: 16,
	},
	photoDropZoneText: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 20,
	},
	infoText: {
		color: colors.text,
		fontSize: 14,
		lineHeight: 21,
	},
	chipRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: spacing.sm,
	},
	chip: {
		backgroundColor: colors.splash,
		borderWidth: 1,
		borderColor: colors.secondaryLight,
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: spacing.sm,
	},
	chipActive: {
		backgroundColor: colors.primary,
		borderColor: colors.primary,
	},
	chipText: {
		color: colors.text,
		fontSize: 12,
	},
	chipTextActive: {
		color: colors.surface,
	},
	rowGap: {
		gap: spacing.sm,
	},
	mapCard: {
		padding: spacing.sm,
	},
	mapFrame: {
		minHeight: 360,
		borderRadius: cornerRadius,
		overflow: 'hidden',
		backgroundColor: colors.splash,
		borderWidth: 1,
		borderColor: colors.secondaryLight,
	},
	mapGrid: {
		...StyleSheet.absoluteFillObject,
		opacity: 0.35,
		backgroundColor: 'transparent',
	},
	mapPulseOne: {
		position: 'absolute',
		top: '25%',
		left: '23%',
		width: 110,
		height: 110,
		borderRadius: 110,
		backgroundColor: 'rgba(242, 32, 31, 0.2)',
	},
	mapPulseTwo: {
		position: 'absolute',
		top: '52%',
		right: '16%',
		width: 86,
		height: 86,
		borderRadius: 86,
		backgroundColor: 'rgba(242, 32, 31, 0.24)',
	},
	mapPulseThree: {
		position: 'absolute',
		bottom: '18%',
		left: '48%',
		width: 72,
		height: 72,
		borderRadius: 72,
		backgroundColor: 'rgba(242, 32, 31, 0.22)',
	},
	mapMarkerOne: {
		position: 'absolute',
		top: '23%',
		left: '25%',
		width: 14,
		height: 14,
		borderRadius: 14,
		backgroundColor: colors.primary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapMarkerTwo: {
		position: 'absolute',
		top: '54%',
		right: '18%',
		width: 14,
		height: 14,
		borderRadius: 14,
		backgroundColor: colors.primary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapMarkerThree: {
		position: 'absolute',
		bottom: '20%',
		left: '50%',
		width: 14,
		height: 14,
		borderRadius: 14,
		backgroundColor: colors.primary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapNestMarker: {
		position: 'absolute',
		top: '33%',
		left: '18%',
		width: 16,
		height: 16,
		borderRadius: 4,
		backgroundColor: colors.secondary,
		borderWidth: 3,
		borderColor: colors.surface,
	},
	mapControls: {
		position: 'absolute',
		top: spacing.md,
		right: spacing.md,
	},
	zoomBadge: {
		position: 'absolute',
		top: spacing.md,
		left: spacing.md,
		backgroundColor: 'rgba(255,255,255,0.96)',
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: spacing.xs,
	},
	countBadge: {
		position: 'absolute',
		bottom: spacing.md,
		right: spacing.md,
		backgroundColor: 'rgba(255,255,255,0.96)',
		borderRadius: cornerRadius,
		paddingHorizontal: spacing.md,
		paddingVertical: spacing.xs,
	},
	badgeText: {
		color: colors.text,
		fontSize: 12,
	},
	historyScreen: {
		flex: 1,
		backgroundColor: colors.background,
	},
	historyHeaderBar: {
		backgroundColor: colors.secondary,
		paddingHorizontal: screenGutter,
		paddingTop: 28,
		paddingBottom: 16,
		minHeight: 78,
		justifyContent: 'flex-end',
	},
	historyHeaderTitle: {
		color: colors.surface,
		fontSize: 22,
		lineHeight: 26,
		textTransform: 'uppercase',
	},
	historyContent: {
		flexGrow: 1,
		paddingHorizontal: screenGutter,
		paddingBottom: screenBottomPadding,
		paddingTop: spacing.lg,
		gap: spacing.lg,
	},
	historySearchCard: {
		borderRadius: cornerRadius,
		borderWidth: 0,
		...unifiedShadow,
	},
	historySearchInputWrap: {
		minHeight: 42,
		borderWidth: 1,
		borderColor: colors.secondaryLight,
		borderRadius: cornerRadius,
		paddingHorizontal: 10,
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: colors.surface,
	},
	historySearchInput: {
		flex: 1,
		color: colors.text,
		fontSize: 14,
		paddingVertical: 0,
	},
	historyFilterButton: {
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: colors.secondary,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 7,
	},
	historyFilterButtonDisabled: {
		opacity: 0.45,
	},
	historyFilterButtonText: {
		color: colors.surface,
		fontSize: 13,
		textTransform: 'uppercase',
	},
	historyRecordCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
		paddingVertical: 12,
		gap: spacing.md,
		...unifiedShadow,
	},
	historyRecordTopRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: spacing.sm,
	},
	historyRecordIdBadge: {
		minWidth: 45,
		height: 26,
		borderRadius: cornerRadius,
		backgroundColor: colors.primary,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 8,
	},
	historyRecordIdText: {
		color: colors.surface,
		fontSize: 12,
	},
	historyRecordDateRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	historyRecordDateText: {
		color: colors.text,
		fontSize: 12,
	},
	historyRecordDateDot: {
		color: colors.text,
		fontSize: 12,
	},
	historyRecordInfoRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	historyRecordInfoText: {
		color: colors.text,
		fontSize: 12,
	},
	historyTagRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	historyTagChip: {
		paddingHorizontal: 10,
		paddingVertical: 5,
		borderRadius: cornerRadius,
		backgroundColor: colors.splash,
	},
	historyTagChipText: {
		color: colors.secondary,
		fontSize: 10,
		textTransform: 'uppercase',
	},
	historyDetailButton: {
		minHeight: 38,
		borderRadius: cornerRadius,
		backgroundColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	historyDetailButtonText: {
		color: colors.surface,
		fontSize: 13,
		textTransform: 'uppercase',
	},
	historyEmptyWrap: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'transparent',
		paddingHorizontal: spacing.md,
	},
	historyLoadingIcon: {
		marginBottom: spacing.sm,
	},
	historyEmptyText: {
		color: colors.muted,
		fontSize: 13,
		textAlign: 'center',
	},
	historyModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(0, 0, 0, 0.28)',
		justifyContent: 'flex-end',
	},
	historyModalCard: {
		backgroundColor: colors.surface,
		borderTopLeftRadius: 12,
		borderTopRightRadius: 12,
		maxHeight: '84%',
	},
	historyModalHeader: {
		minHeight: 60,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: colors.border,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	historyModalTitle: {
		color: colors.secondary,
		fontSize: 22,
		fontWeight: '800',
		textTransform: 'uppercase',
	},
	historyModalContent: {
		paddingHorizontal: 16,
		paddingTop: 14,
		paddingBottom: 18,
		gap: 16,
	},
	historyFilterSection: {
		gap: 8,
	},
	historyFilterSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	historyFilterSectionTitle: {
		color: colors.text,
		fontSize: 13,

		textTransform: 'uppercase',
	},
	historyDateLabelsRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingRight: 12,
	},
	historySmallLabel: {
		color: colors.muted,
		fontSize: 11,

		width: '48%',
	},
	historyDateRow: {
		flexDirection: 'row',
		gap: 8,
	},
	historyDateInputWrap: {
		flex: 1,
		minHeight: 40,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.surface,
		paddingHorizontal: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 6,
	},
	historyDateInput: {
		flex: 1,
		color: colors.text,
		fontSize: 13,
		paddingVertical: 0,
	},
	historySingleInput: {
		minHeight: 40,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.surface,
		paddingHorizontal: 12,
		color: colors.text,
		fontSize: 14,
	},
	historyHalfInput: {
		flex: 1,
		minHeight: 40,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.surface,
		paddingHorizontal: 12,
		color: colors.text,
		fontSize: 14,
	},
	historyBehaviorList: {
		gap: 8,
	},
	historyBehaviorItem: {
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: colors.background,
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 10,
		gap: 10,
	},
	historyBehaviorCheckbox: {
		width: 18,
		height: 18,
		borderRadius: cornerRadius,
		borderWidth: 1.2,
		borderColor: colors.border,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.surface,
	},
	historyBehaviorCheckboxActive: {
		backgroundColor: colors.secondary,
		borderColor: colors.secondary,
	},
	historyBehaviorLabel: {
		color: colors.text,
		fontSize: 16,
	},
	historyModalActions: {
		borderTopWidth: 1,
		borderTopColor: colors.border,
		paddingHorizontal: 16,
		paddingVertical: 10,
		flexDirection: 'row',
		gap: 10,
	},
	historyClearButton: {
		flex: 1,
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: colors.border,
		alignItems: 'center',
		justifyContent: 'center',
	},
	historyClearButtonText: {
		color: colors.text,
		fontSize: 12,

		textTransform: 'uppercase',
	},
	historyApplyButton: {
		flex: 1,
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	historyApplyButtonText: {
		color: colors.surface,
		fontSize: 12,

		textTransform: 'uppercase',
	},
	recordDetailScreen: {
		flex: 1,
		backgroundColor: colors.surface,
	},
	recordDetailHeaderBar: {
		backgroundColor: colors.secondary,
		minHeight: 82,
		paddingTop: 30,
		paddingBottom: 14,
		paddingHorizontal: screenGutter,
		flexDirection: 'row',
		alignItems: 'center',
		gap: spacing.lg,
	},
	recordDetailBackButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	recordDetailHeaderTitle: {
		color: colors.surface,
		fontSize: 22,
		lineHeight: 20,
		textTransform: 'uppercase',
	},
	recordDetailContent: {
		paddingHorizontal: screenGutter,
		paddingTop: spacing.lg,
		paddingBottom: spacing.lg,
		gap: spacing.lg,
	},
	recordDetailNotFoundWrap: {
		flexGrow: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'transparent',
		paddingHorizontal: screenGutter,
		paddingVertical: spacing.lg,
	},
	recordDetailLoadingIcon: {
		marginBottom: spacing.sm,
	},
	recordDetailEmptyText: {
		color: colors.muted,
		fontSize: 14,
		textAlign: 'center',
	},
	recordDetailIdBadge: {
		flexShrink: 0,
		maxWidth: '30%',
		minWidth: 44,
		height: 30,
		borderRadius: cornerRadius,
		backgroundColor: colors.primary,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: spacing.sm,
	},
	recordDetailIdText: {
		color: colors.surface,
		fontSize: 13,
		textTransform: 'uppercase',
	},
	recordDetailCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 18,
		paddingVertical: 18,
		gap: spacing.sm,
		...unifiedShadow,
	},
	recordDetailSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: spacing.sm,
	},
	recordDetailHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: spacing.sm,
	},
	recordDetailInfoHeaderTitle: {
		flex: 1,
	},
	recordDetailSectionTitle: {
		color: colors.secondary,
		fontSize: 15,
		textTransform: 'uppercase',
	},
	recordDetailInfoList: {
		gap: spacing.sm,
	},
	recordDetailInfoRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: spacing.sm,
	},
	recordDetailInfoTextWrap: {
		flex: 1,
	},
	recordDetailInfoLabel: {
		color: colors.muted,
		fontSize: 11,
		textTransform: 'uppercase',
	},
	recordDetailValue: {
		color: colors.text,
		fontSize: 16,
		lineHeight: 20,
	},
	recordDetailCoordinates: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 17,
	},
	recordDetailChipRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	recordDetailChip: {
		borderRadius: cornerRadius,
		backgroundColor: colors.splash,
		paddingHorizontal: 12,
		paddingVertical: 7,
	},
	recordDetailChipText: {
		color: colors.secondary,
		fontSize: 14,
	},
	recordDetailImageGrid: {
		flexDirection: 'row',
		gap: 12,
	},
	recordDetailImagePlaceholder: {
		flex: 1,
		minHeight: 76,
		borderRadius: cornerRadius,
		backgroundColor: colors.border,
		alignItems: 'center',
		justifyContent: 'center',
	},
	profileScreen: {
		flex: 1,
		backgroundColor: colors.background,
	},
	profileHeaderBar: {
		backgroundColor: colors.secondary,
		minHeight: 82,
		justifyContent: 'flex-end',
		paddingBottom: 14,
		paddingHorizontal: screenGutter,
		paddingTop: 30,
	},
	profileSecondaryHeaderBar: {
		backgroundColor: colors.secondary,
		minHeight: 82,
		paddingTop: 30,
		paddingBottom: 14,
		paddingHorizontal: screenGutter,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	profileHeaderBackButton: {
		width: 28,
		height: 28,
		alignItems: 'center',
		justifyContent: 'center',
	},
	profileHeaderTitle: {
		color: colors.surface,
		fontSize: 22,
		lineHeight: 39,

		textTransform: 'uppercase',
	},
	profileContent: {
		paddingHorizontal: screenGutter,
		paddingBottom: screenBottomPadding,
		paddingTop: spacing.lg,
		gap: spacing.lg,
	},
	profileHeroCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
		paddingVertical: 20,
		alignItems: 'center',
		...unifiedShadow,
	},
	profileAvatarCircle: {
		width: 104,
		height: 104,
		borderRadius: 104,
		borderWidth: 2.8,
		borderColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 8,
	},
	profileHeroName: {
		color: colors.text,
		fontSize: 15,
		lineHeight: 18,

		textAlign: 'center',
	},
	profileHeroEmail: {
		color: colors.muted,
		fontSize: 12,
		lineHeight: 15,

		textAlign: 'center',
		marginBottom: 10,
	},
	profileEditButton: {
		minWidth: 114,
		minHeight: 36,
		borderRadius: cornerRadius,
		backgroundColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 18,
	},
	profileEditButtonText: {
		color: colors.surface,
		fontSize: 14,

		textTransform: 'uppercase',
	},
	profileMenuCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 16,
		paddingVertical: 18,
		gap: 10,
		...unifiedShadow,
	},
	profileMenuTitle: {
		color: colors.secondary,
		fontSize: 14,

		textTransform: 'uppercase',
		marginBottom: 2,
	},
	profileMenuItem: {
		minHeight: 42,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
		paddingHorizontal: 8,
	},
	profileMenuItemText: {
		color: colors.text,
		fontSize: 14,
	},
	profileMenuItemTextLogout: {
		color: colors.primary,
		fontSize: 14,
	},
	changePasswordCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
		paddingVertical: 16,
		gap: 14,
		...unifiedShadow,
	},
	changePasswordFieldWrap: {
		gap: 5,
	},
	changePasswordLabelRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	changePasswordLabel: {
		color: colors.text,
		fontSize: 12,

		textTransform: 'uppercase',
	},
	changePasswordInputRow: {
		minHeight: 42,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: colors.secondaryLight,
		backgroundColor: colors.surface,
		paddingLeft: 10,
		paddingRight: 6,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	changePasswordInput: {
		minHeight: 42,
		borderRadius: cornerRadius,
		borderWidth: 1,
		borderColor: colors.border,
		backgroundColor: colors.surface,
		paddingHorizontal: 10,
		color: colors.text,
		fontSize: 13,
	},
	changePasswordInputNoPadding: {
		flex: 1,
		color: colors.text,
		fontSize: 14,
		paddingVertical: 0,
	},
	changePasswordEyeButton: {
		width: 30,
		height: 30,
		alignItems: 'center',
		justifyContent: 'center',
	},
	changePasswordHint: {
		color: colors.muted,
		fontSize: 11,
	},
	changePasswordActionsRow: {
		flexDirection: 'row',
		gap: 10,
		marginTop: 10,
	},
	changePasswordPrimaryAction: {
		flex: 1,
		minHeight: 42,
		borderRadius: cornerRadius,
		backgroundColor: colors.primary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	changePasswordPrimaryActionText: {
		color: colors.surface,
		fontSize: 12,

		textTransform: 'uppercase',
	},
	changePasswordSecondaryAction: {
		flex: 1,
		minHeight: 42,
		borderRadius: cornerRadius,
		backgroundColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	changePasswordSecondaryActionText: {
		color: colors.surface,
		fontSize: 12,

		textTransform: 'uppercase',
	},
	notificationsCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 12,
		paddingVertical: 14,
		gap: 12,
		...unifiedShadow,
	},
	notificationsTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 7,
		paddingHorizontal: 4,
	},
	notificationsTitle: {
		color: colors.secondary,
		fontSize: 13,

		textTransform: 'uppercase',
	},
	notificationsItem: {
		minHeight: 58,
		borderRadius: cornerRadius,
		backgroundColor: colors.background,
		paddingHorizontal: 10,
		paddingVertical: 8,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	notificationsTextWrap: {
		flex: 1,
		gap: 2,
	},
	notificationsItemTitle: {
		color: colors.text,
		fontSize: 14,
	},
	notificationsItemSubtitle: {
		color: colors.muted,
		fontSize: 11,
		lineHeight: 14,
	},
	aboutCard: {
		backgroundColor: colors.surface,
		borderRadius: cornerRadius,
		paddingHorizontal: 14,
		paddingVertical: 16,
		gap: 12,
		...unifiedShadow,
	},
	aboutLogo: {
		alignSelf: 'center',
		width: 210,
		height: 110,
		marginTop: 8,
		marginBottom: 6,
	},
	aboutAppName: {
		color: colors.secondary,
		fontSize: 19,

		textAlign: 'center',
		textTransform: 'uppercase',
	},
	aboutVersion: {
		color: colors.muted,
		fontSize: 14,

		textAlign: 'center',
		marginBottom: 10,
	},
	aboutSection: {
		gap: 6,
	},
	aboutSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	aboutSectionTitle: {
		color: colors.secondary,
		fontSize: 13,

		textTransform: 'uppercase',
	},
	aboutBodyText: {
		color: colors.text,
		fontSize: 13,
		lineHeight: 25,
	},
	aboutBulletRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 6,
	},
	aboutBulletDot: {
		color: colors.primary,
		fontSize: 12,
		lineHeight: 24,
	},
	aboutFooterDivider: {
		height: 1,
		backgroundColor: colors.border,
		marginTop: 6,
	},
	aboutFooterText: {
		color: colors.muted,
		fontSize: 11,
		lineHeight: 15,

		textAlign: 'center',
	},
	profileHero: {
		alignItems: 'center',
	},
	avatarCircle: {
		width: 112,
		height: 112,
		borderRadius: 112,
		backgroundColor: colors.splash,
		borderWidth: 3,
		borderColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	avatarInitial: {
		color: colors.secondary,
		fontSize: 46,
	},
	profileName: {
		color: colors.text,
		fontSize: 20,

		textAlign: 'center',
	},
	profileEmail: {
		color: colors.muted,
		fontSize: 13,
		textAlign: 'center',
	},
	toggleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: spacing.md,
	},
	toggleTextWrap: {
		flex: 1,
		gap: spacing.xs,
	},
	toggleTitle: {
		color: colors.text,
		fontSize: 15,
	},
	toggleSubtitle: {
		color: colors.muted,
		fontSize: 13,
		lineHeight: 19,
	},
	listItem: {
		color: colors.text,
		fontSize: 14,
		lineHeight: 21,
	},
	bottomNav: {
		flexDirection: 'row',
		backgroundColor: colors.surface,
		borderTopWidth: 1,
		borderTopColor: colors.border,
		paddingTop: 8,
		paddingBottom: 10,
		paddingHorizontal: 6,
	},
	bottomNavItem: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
    paddingVertical: 5,
		borderRadius: cornerRadius,
		gap: spacing.xs,
	},
	bottomNavItemActive: {
    backgroundColor: colors.primary,
	},
	bottomNavIcon: {
		marginBottom: -1,
	},
	bottomNavLabel: {
		color: colors.muted,
		fontSize: 10,
		textTransform: 'uppercase',
		textAlign: 'center',
	},
	bottomNavLabelActive: {
		color: colors.surface,
	},
	recordImageModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(0, 0, 0, 0.5)',
		justifyContent: 'center',
		alignItems: 'center',
	},
	recordImageModalCard: {
		backgroundColor: colors.surface,
		borderRadius: 12,
		maxHeight: '90%',
		maxWidth: '95%',
		width: '100%',
		overflow: 'hidden',
	},
	recordImageModalHeader: {
		minHeight: 56,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: colors.border,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	recordImageModalTitle: {
		color: colors.secondary,
		fontSize: 18,
		fontWeight: '800',
		textTransform: 'uppercase',
	},
	recordImageModalContent: {
		paddingHorizontal: 16,
		paddingTop: 16,
		paddingBottom: 16,
		gap: 16,
	},
	recordImageModalImageContainer: {
		borderRadius: 8,
		backgroundColor: colors.background,
		minHeight: 240,
		maxHeight: 320,
		alignItems: 'center',
		justifyContent: 'center',
		overflow: 'hidden',
	},
	recordImageModalImage: {
		width: '100%',
		height: '100%',
	},
	recordImageModalImagePlaceholder: {
		width: '100%',
		height: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.background,
	},
	recordImageModalIndexBadge: {
		alignSelf: 'center',
		backgroundColor: colors.surface,
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
	},
	recordImageModalIndexText: {
		color: colors.text,
		fontSize: 10,
		textTransform: 'uppercase',
	},
	recordImageModalSection: {
		gap: 10,
	},
	recordImageModalSectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	recordImageModalSectionTitle: {
		color: colors.text,
		fontSize: 13,
		fontWeight: '700',
		textTransform: 'uppercase',
	},
	recordImageModalStatusBadge: {
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 8,
		borderWidth: 1,
	},
	recordImageModalStatusText: {
		fontSize: 13,
		fontWeight: '600',
		textTransform: 'uppercase',
	},
	recordImageModalIbisList: {
		gap: 8,
	},
	recordImageModalIbisItem: {
		backgroundColor: colors.background,
		borderRadius: 8,
		paddingHorizontal: 12,
		paddingVertical: 10,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
	},
	recordImageModalIbisColorBadge: {
		width: 32,
		height: 32,
		borderRadius: 6,
		backgroundColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	recordImageModalIbisInfo: {
		flex: 1,
		gap: 2,
	},
	recordImageModalIbisIndex: {
		color: colors.text,
		fontSize: 13,
		fontWeight: '600',
	},
	recordImageModalIbisDetail: {
		color: colors.muted,
		fontSize: 11,
	},
	recordImageModalEmptyState: {
		paddingHorizontal: 12,
		paddingVertical: 16,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.background,
		borderRadius: 8,
	},
	recordImageModalEmptyText: {
		color: colors.muted,
		fontSize: 13,
		textAlign: 'center',
	},
	recordImageModalActions: {
		borderTopWidth: 1,
		borderTopColor: colors.border,
		paddingHorizontal: 16,
		paddingVertical: 12,
		flexDirection: 'row',
		gap: 10,
	},
	recordImageModalCloseButton: {
		flex: 1,
		minHeight: 40,
		borderRadius: cornerRadius,
		backgroundColor: colors.secondary,
		alignItems: 'center',
		justifyContent: 'center',
	},
	recordImageModalCloseButtonText: {
		color: colors.surface,
		fontSize: 13,
		fontWeight: '600',
		textTransform: 'uppercase',
	},
	recordDetailImagePressable: {
		flex: 1,
		minHeight: 76,
		borderRadius: cornerRadius,
		backgroundColor: colors.border,
		overflow: 'hidden',
	},
	recordDetailImage: {
		width: '100%',
		height: '100%',
	},
	recordImageModalSummaryGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
		rowGap: 10,
		columnGap: 8,
		marginBottom: 6,
	},
	recordImageModalAccuracyItem: {
		flex: 1,
		minWidth: '48%',
		paddingHorizontal: 10,
		paddingVertical: 8,
		backgroundColor: colors.background,
		borderRadius: 6,
		alignItems: 'center',
		justifyContent: 'center',
	},
	recordImageModalAccuracyLabel: {
		fontSize: 11,
		color: colors.muted,
		fontWeight: '500',
		marginBottom: 4,
		textAlign: 'center',
	},
	recordImageModalAccuracyValue: {
		fontSize: 14,
		fontWeight: '700',
		color: colors.secondary,
	},
	recordImageModalIbisItemExpanded: {
		paddingHorizontal: 12,
		paddingVertical: 10,
		marginBottom: 8,
		backgroundColor: colors.background,
		borderRadius: 8,
		borderLeftWidth: 3,
		borderLeftColor: '#125ED0',
	},
	recordImageModalIbisHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		marginBottom: 10,
	},
	recordImageModalIbisDetails: {
		gap: 6,
	},
	recordImageModalDetailRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingVertical: 4,
	},
	recordImageModalDetailLabel: {
		fontSize: 12,
		color: colors.muted,
		fontWeight: '500',
	},
	recordImageModalDetailValue: {
		fontSize: 12,
		color: colors.secondary,
		fontWeight: '600',
	},
	recordImageModalAccuraciesContainer: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 6,
		marginTop: 8,
		paddingTop: 8,
		borderTopWidth: 1,
		borderTopColor: colors.border,
	},
	recordImageModalAccuracySmall: {
		flex: 1,
		minWidth: 65,
		paddingHorizontal: 6,
		paddingVertical: 6,
		backgroundColor: colors.splash,
		borderRadius: 4,
		alignItems: 'center',
		justifyContent: 'center',
	},
	recordImageModalAccuracySmallLabel: {
		fontSize: 10,
		color: '#666666',
		fontWeight: '500',
		marginBottom: 2,
	},
	recordImageModalAccuracySmallValue: {
		fontSize: 11,
		fontWeight: '700',
		color: '#125ED0',
	},
})
