export type ScreenId =
  | 'splash'
  | 'welcome'
  | 'login'
  | 'register-email'
  | 'register-password'
  | 'home'
  | 'register'
  | 'maps'
  | 'history'
  | 'record-detail'
  | 'profile'
  | 'edit-profile'
  | 'change-password'
  | 'notifications'
  | 'about';
